services:
  medrag:
    container_name: medrag-api

    build:
      context: ..
      dockerfile: docker/Dockerfile

    image: medrag:latest

    restart: unless-stopped

    ports:
      - "8000:8000"

    volumes:
      - ../logs:/app/logs

    depends_on:
      - qdrant

    networks:
      - medrag-network

  qdrant:
    image: qdrant/qdrant:latest

    container_name: medrag-qdrant

    restart: unless-stopped

    ports:
      - "6333:6333"
      - "6334:6334"

    volumes:
      - qdrant_data:/qdrant/storage

    networks:
      - medrag-network

networks:
  medrag-network:
    driver: bridge

volumes:
  qdrant_data: